version: "3.8"
services:
  app:
    build:
      context: .
    stop_grace_period: 3s
    environment:
      DATABASE_URL: mongodb://mongodb:27017/brainsoft?replicaSet=rs0
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:7-jammy
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27017",
        "--quiet",
        "--logpath",
        "/dev/null",
      ]
    ports:
      - "27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb"
    healthcheck:
      test: test $$(mongosh --port 27017 --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongodb:27017\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s

volumes:
  mongodb-data:
  mongodb-config:
