version: "3.8"
services:
  dev:
    build:
      context: ..
      target: dev
    working_dir: /home/node/app
    command: tail -f /dev/null
    stop_grace_period: 1s
    environment:
      APP_ENV: local
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
      DATABASE_URL: mongodb://mongodb:27017/brainsoft?replicaSet=rs0
      PORT: ${PORT}
    volumes:
      - ..:/home/node/app
      - ${DC_SSH:-~/.ssh}:/root/.ssh
      - ${DC_GIT_CONFIG:-/dev/null}:/root/.devcontainer/.gitconfig
      - ${DC_NPM_RC:-/dev/null}:/root/.devcontainer/.npmrc

  mongodb:
    image: mongo:7-jammy
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb"
    healthcheck:
      test: test $$(mongosh --port 27017 --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongodb:27017\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s

volumes:
  mongodb-data:
  mongodb-config:
